export { default as Table } from './Table/Table'
export { default as Thead } from './Thead/Thead'
export { default as Tbody } from './Tbody/Tbody'
export { default as Tr } from './Tr/Tr'
export { default as Td } from './Td/Td'